=== sbalajisathya/mcp/credit-card-apply/src/main/resources/application-form-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "addresses": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "addressType": {
              "type": "string",        
            "enum": [
              "HOME",
              "OFFICE"
            ]
            },
            "city": {
              "type": "string"
            },
            "country": {
              "type": "string"
            },
            "doorNo": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "streetName": {
              "type": "string"
            },
            "zipCode": {
              "type": "string"
            }
          },
          "required": [
            "addressType",
            "city",
            "country",
            "doorNo",
            "state",
            "streetName",
            "zipCode"
          ]
        }
      ]
    },
    "contactDetail": {
      "type": "object",
      "properties": {
        "emailId": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "fullName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "mobileNumber": {
          "type": "string"
        }
      },
      "required": [
        "emailId",
        "firstName",
        "fullName",
        "lastName",
        "mobileNumber"
      ]
    },
   
    "personalDetail": {
      "type": "object",
      "properties": {
        "citizenship": {
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string"
        },
        "fatherName": {
          "type": "string"
        },
        "maritalStatus": {
          "type":  "string",        
            "enum": [
              "SINGLE",
              "MARRIED"
            ]
        },
        "pancard": {
          "type": "string"
        },
        "residentialStatus": {
          "type": "string"
        }
      },
      "required": [
        "citizenship",
        "dateOfBirth",
        "fatherName",
        "maritalStatus",
        "pancard",
        "residentialStatus"
      ]
    },
    "professionalDetail": {
      "type": "object",
      "properties": {
        "companyName": {
          "type": "string"
        },
        "designationName": {
          "type": "string"
        },
        "grossAnnualIncome": {
          "type": "number"
        },
        "professionName": {
          "type": "string"
        }
      },
      "required": [
        "companyName",
        "designationName",
        "grossAnnualIncome",
        "professionName"
      ]
    }
  },
  "required": [
    "addresses",
    "contactDetail",
    "personalDetail",
    "professionalDetail"
   
  ]
}

=== sbalajisathya/mcp/credit-card-apply/src/test/resources/applicationForm.json
{
    "contactDetail": {
        "firstName": "Ram",
        "lastName": "Sathyanarayanan",
        "fullName": "Ram Sathyanarayanan",
        "mobileNumber": "987-654-321",
        "emailId": "test@gmail.com"
    },
    "personalDetail": {
        "fatherName": "Sathyanarayanan",
        "dateOfBirth": "20-01-1940",
        "maritalStatus": "SINGLE",
        "citizenship": "Indian",
        "residentialStatus": "Chennai",
        "pancard": "ABCDEFG"
    },
    "professionalDetail": {
        "professionName": "Software Developer",
        "companyName": "QBC corp",
        "designationName": " Associcate",
        "grossAnnualIncome": 600000
    },
    "addresses": [{
            "doorNo": "91",
            "streetName": "Kumara St",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "zipCode": "600091",
            "addressType": "HOME"
        }
    ]
}
